language: python
python:
    - "2.7"

install: 
    pip install -r requirements.txt

script:
 - pip install -r test-requirements.txt
 - make coverage

after_success:
 - pip install coveralls
 - coveralls
