# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 15:46
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160528_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(verbose_name='timezone'),
        ),
    ]
