# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateTimeField(blank=True, help_text='Date image was taken; is obtained from the image EXIF data.', null=True, verbose_name='date taken'),
        ),
        migrations.AlterField(
            model_name='image',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='view count'),
        ),
    ]
